version: '3.8'

services:
  sqlite-db:
    image: nouchka/sqlite3:latest
    container_name: ailos-sqlite
    volumes:
      - ./data:/root/db
    command: sleep infinity
    networks:
      - ailos-network

  encrypted-id-test-api:
    build:
      context: .
      dockerfile: src/Ailos.EncryptedId.TestApi/Dockerfile
    container_name: ailos-encrypted-id-test-api
    ports:
      - "5080:80"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - sqlite-db
    networks:
      - ailos-network

  conta-corrente-api:
    build:
      context: .
      dockerfile: src/Ailos.ContaCorrente.Api/Dockerfile
    container_name: ailos-conta-corrente-api
    ports:
      - "5081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/ailos.db
      - ENCRYPTED_ID_SECRET=ENCRYPTED_ID_SECRET
      - JwtSettings__Secret=JwtSettings__Secret
      - JwtSettings__Issuer=AilosContaCorrenteApi
      - JwtSettings__Audience=AilosClient
      - JwtSettings__ExpirationMinutes=60
    volumes:
      - ./data:/app/data
      - ./scripts/sql:/app/scripts/sql
    depends_on:
      - sqlite-db
    networks:
      - ailos-network

networks:
  ailos-network:
    driver: bridge